language: android

node_js:
  - 5.5

sudo: false

branches:
  only:
  - master

install:
  - sudo apt-get install npm
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant

release:
  - exit 0
