language: android

node_js:
  - 7.0

sudo: false

branches:
  only:
  - master

install:
  - sudo apt-get install npm
  - sudo npm install -g ionic cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
